FROM ubuntu/apache2:2.4-20.04_beta
USER root
RUN ["a2enmod", "proxy_http"]
RUN ["a2enmod", "ssl"]
RUN ["a2enmod", "rewrite"]
RUN ["mkdir", "-p", "/etc/letsencrypt/live/stgstudymoa.shop"]
COPY ./studymoa_web/000-default.conf /etc/apache2/sites-available/000-default.conf