version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/studymoa-server
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/studymoa-server
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 6000
      runas: root