version: "3.9"
services:
  web:
    # ubuntu@ip-172-31-16-247:/etc/apache2$ apache2 -v
    # Server version: Apache/2.4.29 (Ubuntu)
    # Server built:   2022-03-16T16:53:42
    # image: httpd:2.4.29
    # image: ubuntu/apache2:2.4-20.04_beta
    container_name: web
    build:
      context: ./studymoa_web
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./studymoa_web/000-default.conf:/etc/apache2/sites-available/000-default.conf
      # - ./studymoa_web/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./studymoa_web/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      # - ./studymoa_web/default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf
      - ./studymoa_home:/var/www/html
      - ./studymoa_admin/build:/var/www/html/admin
      - ./pem:/etc/letsencrypt/live/stgstudymoa.shop
      - ./studymoa_web/options-ssl-apache.conf:/etc/letsencrypt/options-ssl-apache.conf
      - /etc/localtime:/etc/localtime:ro
    # environment:
    #   - CURRENT=${CURRENT}
    # apache 000-default.conf 하드코딩으로 변경 deploy.sh 참조
    depends_on:
      - "${CURRENT}"
  blue:
    container_name: blue
    build:
      context: ./studymoa_api_mock/blue
      dockerfile: Dockerfile.mock.api
    ports:
      - "4000:4000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure:5
  green:
    container_name: green
    build:
      context: ./studymoa_api_mock/green
      dockerfile: Dockerfile.mock.api
    ports:
      - "4001:4000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure:5

  # 디버깅 목적
  # debug:
  #   image: praqma/network-multitool
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro

  # admin:
  #   build:
  #     context: ./studymoa_admin
  #     dockerfile: Dockerfile.admin
  #   volumes:
  #     - ./studymoa_admin/build:admin-html

volumes:
  admin-html: