FROM node:12.18.2-slim

EXPOSE 4000

WORKDIR /usr/app

# 캐싱
COPY package.json package.json
RUN npm install
# 코드 복사
COPY . .
# TimeZone 설정
ENV TZ Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# CMD [ "npm", "run", "start" ]
RUN npm install -g json-server
CMD [ "json-server", "--watch", "data.json", "--port", "4000", "--host", "0.0.0.0" ]