name: Staging-Deploy
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      - name: zip create 
        run: zip -qq -r ./build-server.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp --region ${AWS_REGION} ./build-server.zip s3://kitworks/deploy/build-server.zip
      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name stg-studymoa-admin
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name stg-studymoa-admin
          --s3-location bucket=kitworks,key=deploy/build-server.zip,bundleType=zip
